## Numpy library

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in the array

In [7]:
## zero d array for single element
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


## 1 D array

In [8]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


## 2d Array

In [ ]:
arr=np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print(arr.ndim)

In [13]:
arr=np.array([[1,2,4.45,3,4],[4,4.5,5,6,7]])
print(arr)
print(arr.ndim)

[[1.   2.   4.45 3.   4.  ]
 [4.   4.5  5.   6.   7.  ]]
2


## 3 d array

In [17]:
arr=np.array([[[1,234,45],[2,4,453]],[[1,234,523],[23,234,534]]]) ## we count square brackets for counting dimensions
print(arr)
print(arr.ndim)

[[[  1 234  45]
  [  2   4 453]]

 [[  1 234 523]
  [ 23 234 534]]]
3


## Higher dimensional arrays
an array can have any number of dimensions.
when the array is created, you can define the number of dimensions by using thr ndim argument
# creating an array with 5 dimensions and verify that it has 5 dimensions or not:

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## numpy array indexing
Array indexing is the same as accessing an array element
you can access an array element by reffering to its index number
The indexes in numpy arrays start with 0, meaning that the first element has index 0, and the second index 1 etc
## Get the first element from the following array:

In [12]:
arr = np.array([1,2,3,4])
print(arr[0])

1


## Question) Get third and sixth and eighth element from the following array and add them.


In [13]:
m=np.array([41,87,34,56.8,39.23,90,15,10,19,56])
print("3rd ele:",m[2])
print("6th ele:",m[5])
print("8th ele:",m[7])
print("sum of these elements are", m[2]+m[5]+m[7])

3rd ele: 34.0
6th ele: 90.0
8th ele: 10.0
sum of these elements are 134.0


## Access the third element of the second array of the first array:


In [14]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])


6


In [16]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])

12
