## Numpy part 2
## slicing in numpy


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


## slicing in 2d array

In [5]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [6]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


## checking the data type of an array

In [8]:
arr=np.array([1,2,3,4,5,6,7])
print(arr.dtype)

int64


In [9]:
arr=np.array(['animals','bat','cat'])
print(arr.dtype)

<U7


## creating array with a defined data types

In [11]:
arr=np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## create an array with data type 4 byte integer

In [12]:
arr=np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Numpy array shape
the shape of an array is the number of elements in each dimensions

In [13]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [14]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[4,5,7,9]]])
print(arr.shape)

(1, 3, 4)


## joining numpy arrays

In [15]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


## join 2D array

In [17]:
arr1= np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
arr1= np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis =0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Splitting Numpy Arrays
### splitting the array in 3 parts

In [3]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Spliting the array in 4 parts

In [4]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Ravel & flatten
converts multidimensional array into 1D array

In [7]:
m= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print("dimension is", m.ndim)
n=m.ravel()
print(n)
print("now the new dimensions is", n.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension is 2
[1 2 3 4 5 6 7 8 9]
now the new dimensions is 1


In [12]:
b=np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
print(b)
print("dimensions of b is", b.ndim)
a=b.flatten()
print(a)
print("now the new dim is",a.ndim)
#a=b.ravel()
#print("now the new dim is", a.ndim)
#print(a)

[[[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]]
dimensions of b is 4
[1 2 3 4 1 2 3 4 1 2 3 4]
now the new dim is 1


## unique function

In [13]:
k=np.array([1,2,3,1,2,4,5,2,6,7,4,3,5,6,7,2,4,5,7,5,3,2,4,5,7,76,5,4,3,2])
print(k)
x=np.unique(k)
print(x)

[ 1  2  3  1  2  4  5  2  6  7  4  3  5  6  7  2  4  5  7  5  3  2  4  5
  7 76  5  4  3  2]
[ 1  2  3  4  5  6  7 76]


In [15]:
k=np.array([1,2,3,1,2,4,5,2,6,7,4,3,5,6,7,2,4,5,7,5,3,2,4,5,7,76,5,4,3,2])
print(k)
x=np.unique(k, return_index=True, return_counts=True)
print(x)

[ 1  2  3  1  2  4  5  2  6  7  4  3  5  6  7  2  4  5  7  5  3  2  4  5
  7 76  5  4  3  2]
(array([ 1,  2,  3,  4,  5,  6,  7, 76]), array([ 0,  1,  2,  5,  6,  8,  9, 25]), array([2, 6, 4, 5, 6, 2, 4, 1]))


## Delete

In [16]:
a=np.array([12,13,14,15])
d=np.delete(a,[1])
print(d)

[12 14 15]


In [23]:
x=np.array([[2,7,9,6,8],[2,3,5,56,45],[32,3,5,6,43]])
print(x)
print()
m=np.delete(x,1, axis=0)
print(m)

[[ 2  7  9  6  8]
 [ 2  3  5 56 45]
 [32  3  5  6 43]]

[[ 2  7  9  6  8]
 [32  3  5  6 43]]
